#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;

use App\Services\Workerman\ServerService;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require dirname(__DIR__) . '/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once dirname(__DIR__) . '/bootstrap/app.php';

// コンテナから config を取得できるようにする
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

$serverService = app(ServerService::class);
$serverService->start();

